// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsBindgen
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "";



        [DllImport(__DllName, EntryPoint = "init_my_special_context", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool init_my_special_context(my_special_context** src);

        [DllImport(__DllName, EntryPoint = "free_my_special_context", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool free_my_special_context(my_special_context* src);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct my_special_context
    {
    }



}
    